sync_active_subscriptions_job:
  cron: "*/30 * * * *"
  class: "SyncSubscriptionsJob"
  queue: generatorss

clean_old_tweets_job:
  cron: "0 0 * * *"
  class: "CleanOldRssItemsJob"
  queue: generatorss
