user = User.create!(email: "rien@croonenborghs.net", password: "sparrows are fatties", password_confirmation: "sparrows are fatties")

Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/TheOnion")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/joelycett")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/newsycombinator")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/slashdot")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/Oatmeal")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/dhh")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "https://twitter.com/NileRed2")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@internetofshit")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@consultingcmdy")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@railsconf")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@rubyinside")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@rails")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@josevalim")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@aboutrails")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@thoughtbot")
Twitter::CreateSubscriptionService.call(user: user, url_or_handle: "@rubyflow")

YoutubeChannel::CreateSubscriptionService.call(user: user, url: "https://www.youtube.com/c/MaxFosh")
YoutubeChannel::CreateSubscriptionService.call(user: user, url: "https://www.youtube.com/c/MikeyChenX")
YoutubeChannel::CreateSubscriptionService.call(user: user, url: "https://www.youtube.com/c/OwlKitty")

Website::CreateSubscriptionService.call(user: user, url: "https://badjokesbyjeff.tumblr.com")
